### ISSUE TITLE
Custom parser usage

### ISSUE THREAD

**Issue by dhowe** [datalust/superpower#60]
I find several examples of custom tokenizers ([here for example](https://github.com/serilog/serilog-filters-expressions/blob/master/src/Serilog.Filters.Expressions/Filters/Expressions/Parsing/FilterExpressionTokenizer.cs#L64)), but none of custom (procedural) parsers. Is there an example somewhere, or is this a bad idea?

**Comment by nblumhardt** [comment]
Hi! I'm not 100% sure I'm on the same page, but I think that most of the combinators in https://github.com/datalust/superpower/blob/dev/src/Superpower/Combinators.cs, and the implementation of all of the parsers under the `/Parsers` folder, qualify as custom procedural parsers. There's not much general structure to them, because by their nature, the things that can't be implemented nicely/efficiently by combining other parsers all look pretty different.

HTH!

**Comment by dhowe** [comment]
Right, I guess I meant procedurally-structured, like the FilterExpressionTokenizer in serilog

**Comment by nblumhardt** [comment]
Closing this one as stale, hope you found some examples to unblock this 👍
