### ISSUE TITLE
How to only return what can be parsed in a TokenizerBuilder

### ISSUE THREAD

**Issue by hwalkenshaw** [datalust/superpower#91]
Lets say I want to execute the following:

```csharp
            var tokenizer = new TokenizerBuilder<SqlToken>()
                .Ignore(Span.WhiteSpace)
                .Match(Character.Letter.Many(), SqlToken.Keyword)
                .Build();

            var tokens = tokenizer.Tokenize("select 1 + 23");
            foreach (var token in tokens)
            {
                Console.WriteLine(token);
            }
```

Currently it is failing because it doesnt know how to parse the remainder("1 + 23").

`Superpower.ParseException: 'Zero-width tokens are not supported; token keyword at position 7 (line 1, column 8).'`

Is there a way to tell superpower to only parse what it can and ignore anything else? Or is the only way to supply parsers for what I want to ignore?

**Comment by nblumhardt** [comment]
Hi @hwalkenshaw,

There's no direct way to do it, but you might have some success declaring a `SqlToken.Unknown` value.

First, though - the exception you're hitting is because `Character.Letter.Many()` allows zero-width matches, i.e. `""` would be an infinite set of `SqlToken.Keyword`s using this matcher. Superpower picks that up and throws an exception in that case.

You probably want `Character.Letter.AtLeastOnce()` rather than `Many()` in this rule.

To add `SqlToken.Unknown` looks something like:

```csharp
            var tokenizer = new TokenizerBuilder<SqlToken>()
                .Ignore(Span.WhiteSpace)
                .Match(Character.Letter.AtLeastOnce(), SqlToken.Keyword)
                .Match(Character.Matching(ch => !char.IsWhiteSpace(ch), "token content"), SqlToken.Unknown)
                .Build();
```

HTH!

**Comment by nblumhardt** [comment]
Howdy! I'll assume the above got you unblocked; let me know if it raised more questions than it answered :-) .. Cheers!
